 name: "Deploy to the host"

 on:
  push:
    branches:
      - main
 jobs:
  deploy:
   runs-on: ubuntu-latetst

   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload to FTF
      uses: Sankirkland/FTP-Deploy_Action@4.1.0
      with:
       ftp_server: ftpupload.net
       ftp_username: if0_36632233
       ftp_password: MBKb12RKXIE
       local-dir: "/"
       
